"""Models module."""

from backend.models.schemas import (
    VCFFileResponse,
    VCFFileList,
    VCFFileCreate,
    VariantResponse,
    VariantListResponse,
    VariantFilter,
    VariantStats,
    VariantCreate,
    AnalysisRequest,
    ISMRequest,
    BatchAnalysisRequest,
    AnalysisResultResponse,
    VariantAnalysisResponse,
    BatchJobResponse,
    ClinVarAnnotationResponse,
    PharmGKBAnnotationResponse,
    PharmaGeneReport,
    PharmacogenomicsPanel,
    DiseaseRiskVariant,
    DiseaseRiskPanel,
)
from backend.models.database import (
    VCFFile,
    Variant,
    AnalysisResult,
    ClinVarAnnotation,
    PharmGKBAnnotation,
)

__all__ = [
    # Schema classes
    "VCFFileResponse",
    "VCFFileList",
    "VCFFileCreate",
    "VariantResponse",
    "VariantListResponse",
    "VariantFilter",
    "VariantStats",
    "VariantCreate",
    "AnalysisRequest",
    "ISMRequest",
    "BatchAnalysisRequest",
    "AnalysisResultResponse",
    "VariantAnalysisResponse",
    "BatchJobResponse",
    "ClinVarAnnotationResponse",
    "PharmGKBAnnotationResponse",
    "PharmaGeneReport",
    "PharmacogenomicsPanel",
    "DiseaseRiskVariant",
    "DiseaseRiskPanel",
    # Database models
    "VCFFile",
    "Variant",
    "AnalysisResult",
    "ClinVarAnnotation",
    "PharmGKBAnnotation",
]
